name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Use custom shell with -l so .bash_profile is sourced which loads intel/oneapi/setvars.sh
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  Intel:
    runs-on: ubuntu-latest
    env:
      CC: icc
      FC: ifort
      CXX: icpc
    strategy:
      fail-fast: true
      matrix:
        compilers: ["CC=icc FC=ifort", "CC=icx FC=ifx"]
        switch: [Ifremer1, NCEP_st2, NCEP_st4, ite_pdlib, NCEP_st4sbs, NCEP_glwu, OASACM, UKMO, MULTI_ESMF]
        
    steps:
      - name: install-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libaec-dev libpng-dev zlib1g-dev libjpeg-dev doxygen
          cd /tmp
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install intel-oneapi-dev-utilities intel-oneapi-openmp intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
          echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

      # See https://software.intel.com/content/www/us/en/develop/articles/oneapi-repo-instructions.html
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libaec-dev libpng-dev zlib1g-dev libjpeg-dev doxygen
        cd /tmp
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install intel-oneapi-dev-utilities intel-oneapi-openmp intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
        echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

      - name: checkout-ww3
        if: steps.cache-env.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
            path: ww3

      # Cache spack, OASIS, and compiler
      # No way to flush Action cache, so key may have # appended
      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
            work_oasis3-mct
            /opt/intel
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('ww3/model/ci/spack_intel.yaml') }}-1

      # Build WW3 spack environment
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          # Install NetCDF, ESMF, g2, etc using Spack
          . /opt/intel/oneapi/setvars.sh
          git clone -c feature.manyFiles=true https://github.com/JCSDA/spack.git
          source spack/share/spack/setup-env.sh
          ln -s $(realpath $(which gcc)) spack/lib/spack/env/intel/gcc # spack/make bug in ESMF
          spack env create ww3-intel ww3/model/ci/spack_intel.yaml
          spack env activate ww3-intel
          spack compiler find
          sudo apt install cmake
          spack external find
          spack add intel-oneapi-mpi
          spack config add "packages:all:require:['%intel']"
          spack concretize
          spack install --dirty -v --fail-fast
          spack clean --all

      - name: build-oasis
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          . /opt/intel/oneapi/setvars.sh
          source spack/share/spack/setup-env.sh
          spack env activate ww3-intel
          export WWATCH3_DIR=${GITHUB_WORKSPACE}/ww3/model
          export OASIS_INPUT_PATH=${GITHUB_WORKSPACE}/ww3/regtests/ww3_tp2.14/input/oasis3-mct
          export OASIS_WORK_PATH=${GITHUB_WORKSPACE}/ww3/regtests/ww3_tp2.14/input/work_oasis3-mct
          cd ww3/regtests/ww3_tp2.14/input/oasis3-mct/util/make_dir
          ${{ matrix.compilers }} cmake .
          make
          cp -r ${GITHUB_WORKSPACE}/ww3/regtests/ww3_tp2.14/input/work_oasis3-mct ${GITHUB_WORKSPACE}

      - name: checkout-ww3
        uses: actions/checkout@v3
        with:
            path: ww3

      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
            work_oasis3-mct
            /opt/intel
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('ww3/model/ci/spack_intel.yaml') }}-1

      - name: build-ww3
        run: |
          . /opt/intel/oneapi/setvars.sh
          source spack/share/spack/setup-env.sh
          spack env activate ww3-intel
          cd ww3
          export CC=mpiicc
          export FC=mpiifort
          export OASISDIR=${GITHUB_WORKSPACE}/work_oasis3-mct
          mkdir build && cd build
          if [[ ${{ matrix.switch }} == "MULTI_ESMF" ]]; then
            cmake .. -DMULTI_ESMF=ON -DSWITCH=multi_esmf
          else
            cmake .. -DSWITCH=${{ matrix.switch }}
          fi
          make -j2 VERBOSE=1
